'use strict';const $=id=>document.getElementById(id),T=window.SHA256_TRACE;let p=0,timer=null;
const hex=(x,n=8)=>(x>>>0).toString(16).padStart(n,'0');
const frames=[
{chapter:'1 · Metinden bayta',title:'“merhaba” → 7 UTF-8 baytı',explanation:'Her harfin bayt değeri SHA-256 girişidir.',bytes:T.data,details:T.data.map((v,i)=>`${T.text[i]} → ${v} → ${hex(v,2)}`).join('\n'),cards:[['Metin',T.text],['Bayt sayısı',T.data.length]]},
{chapter:'2 · Dolgu',title:'Önce 80 ekle',explanation:'Mesajın sonuna tek bir 1 biti eklenir. Bayt sınırında bu 10000000₂ = 80₁₆ olur.',bytes:T.padded.slice(0,8),marker:7,details:'6d 65 72 68 61 62 61 | 80\n                         ↑ tek 1 biti, ardından sıfırlar'},
{chapter:'2 · Dolgu',title:'Bloku 64 bayta tamamla',explanation:'Son 8 bayt uzunluk için ayrılır; araya sıfır baytları eklenir.',bytes:T.padded,marker:7,lengthStart:56,details:'7 veri baytı + 1 adet 80 + 48 adet 00 + 8 bayt uzunluk = 64 bayt'},
{chapter:'2 · Dolgu',title:'Uzunluk: 56 bit',explanation:'“merhaba” 7 bayt = 56 bittir. Son 8 bayta büyük uçlu tamsayı olarak yazılır.',bytes:T.padded,lengthStart:56,details:'56 = 0000000000000038₁₆\nSon 8 bayt: 00 00 00 00 00 00 00 38'},
{chapter:'3 · Mesaj planı',title:'İlk 16 kelimeyi bloktan oku',explanation:'64 bayt, 16 adet 32 bitlik kelimeye ayrılır.',details:T.words.slice(0,16).map((v,i)=>`W${i.toString().padStart(2,'0')} = ${hex(v)}`).join('\n'),cards:[['W0',hex(T.words[0])],['W1',hex(T.words[1])],['W15',hex(T.words[15])]]},
{chapter:'3 · Mesaj planı',title:'W16…W63 değerlerini üret',explanation:'Önceki kelimeler döndürme, kaydırma ve toplama ile genişletilir.',details:'W[t] = σ1(W[t−2]) + W[t−7] + σ0(W[t−15]) + W[t−16] mod 2³²\n\nW16 = '+hex(T.words[16])+'\nW63 = '+hex(T.words[63])},
{chapter:'4 · Başlangıç durumu',title:'Sekiz başlangıç kelimesi',explanation:'a…h kayıtları SHA-256 standardındaki sabit başlangıç değerleriyle başlar.',state:T.rounds[0].before,details:'a b c d e f g h\n'+T.rounds[0].before.map(hex).join(' ')},
...T.rounds.map(r=>({chapter:'5 · 64 tur',title:`Tur ${r.t+1}/64`,explanation:'Bu tur W[t] ve K[t] ile sekiz durum kelimesini günceller.',round:r.t,state:r.after,details:`W${r.t} = ${hex(r.w)}\nK${r.t} = ${hex(r.k)}\nΣ1(e) = ${hex(r.S1)}\nCh(e,f,g) = ${hex(r.ch)}\nT1 = h + Σ1(e) + Ch + K + W = ${hex(r.temp1)}\nΣ0(a) = ${hex(r.S0)}\nMaj(a,b,c) = ${hex(r.maj)}\nT2 = Σ0(a) + Maj = ${hex(r.temp2)}\n\nyeni a = T1 + T2 = ${hex(r.after[0])}\nyeni e = d + T1 = ${hex(r.after[4])}`})),
{chapter:'6 · Özet',title:'256 bitlik SHA-256 özeti',explanation:'Son durum başlangıç değerlerine eklenir ve sekiz kelime yan yana yazılır.',state:T.state,details:T.state.map((v,i)=>`H${i} = ${hex(v)}`).join('\n')+'\n\n'+T.digest,cards:[['Hex uzunluğu','64 karakter'],['Bit uzunluğu','256 bit']]}
];
function chapters(){for(const c of new Set(frames.map(f=>f.chapter))){const o=document.createElement('option');o.value=o.textContent=c;$('chapter').append(o)}for(let i=0;i<64;i++){const o=document.createElement('option');o.value=i;o.textContent=i+1;$('round').append(o)}}
function stop(){clearInterval(timer);timer=null;$('play').textContent='Oynat'}
function render(){const f=frames[p];$('step').max=frames.length-1;$('step').value=p;$('counter').textContent=`${f.chapter} · Adım ${p+1}/${frames.length}`;$('chapter').value=f.chapter;$('title').textContent=f.title;$('explanation').textContent=f.explanation;$('details').textContent=f.details;$('cards').replaceChildren();for(const [a,b] of f.cards||[]){const d=document.createElement('div');d.className='sha-card';d.innerHTML='<span></span><strong></strong>';d.children[0].textContent=a;d.children[1].textContent=b;$('cards').append(d)}$('bytes').hidden=!f.bytes;if(f.bytes)$('bytes').innerHTML=f.bytes.map((v,i)=>`<span class="sha-byte ${i===f.marker?'marker':''} ${i>=f.lengthStart?'length':''}">${hex(v,2)}</span>`).join('');$('state').hidden=!f.state;$('state').replaceChildren();for(const [i,v] of (f.state||[]).entries()){const d=document.createElement('div');d.className='sha-word';d.textContent='abcdefgh'[i]+'\n'+hex(v);$('state').append(d)}$('round').value=f.round??0;$('prev').disabled=p===0;$('next').disabled=p===frames.length-1;$('result').hidden=p!==frames.length-1;$('result').textContent=T.digest}
$('next').onclick=()=>{stop();p=Math.min(p+1,frames.length-1);render()};$('prev').onclick=()=>{stop();p=Math.max(p-1,0);render()};$('reset').onclick=()=>{stop();p=0;render()};$('step').oninput=()=>{stop();p=+$('step').value;render()};$('chapter').onchange=()=>{stop();p=frames.findIndex(f=>f.chapter===$('chapter').value);render()};$('round').onchange=()=>{stop();p=7+(+$('round').value);render()};$('play').onclick=()=>{if(timer){stop();return}if(p===frames.length-1)p=0;$('play').textContent='Duraklat';timer=setInterval(()=>{p++;render();if(p===frames.length-1)stop()},1000)};chapters();render();

// Ders görünümü: algoritmanın ana fikrini altı kısa adımda göster.
frames.splice(0, frames.length,
  {chapter:'1 · Girdi',title:'“merhaba” metnini al',explanation:'Özetini çıkaracağımız veri budur.',details:'merhaba',cards:[['Girdi','merhaba'],['Karakter','7']]},
  {chapter:'2 · Baytlar',title:'Metni baytlara çevir',explanation:'Bilgisayar metni sayısal baytlar olarak işler.',bytes:T.data,details:'m  e  r  h  a  b  a\n6d 65 72 68 61 62 61'},
  {chapter:'3 · Hazırlık',title:'Veriyi blok hâline getir',explanation:'SHA-256, veriyi işlemeye uygun 512 bitlik bir bloka tamamlar.',details:'Mesaj + dolgu + mesaj uzunluğu → 512 bitlik blok',cards:[['Asıl veri','7 bayt'],['Hazırlanan blok','64 bayt']]},
  {chapter:'4 · Karıştırma',title:'64 tur karıştır',explanation:'Bloktaki bitler sabit kurallarla karıştırılır. Her turun iç hesabını burada açmıyoruz.',details:'512 bitlik blok → 64 karıştırma turu → 256 bitlik sonuç',cards:[['Tur','64'],['Blok','512 bit']]},
  {chapter:'5 · Sonuç',title:'256 bitlik özeti üret',explanation:'Sonuç 32 bayt, yani 64 hexadecimal karakterdir.',details:T.digest,cards:[['Uzunluk','256 bit'],['Hex karakter','64']]},
  {chapter:'6 · Kullanım',title:'Değişikliği fark et',explanation:'Küçük bir değişiklik farklı bir özet üretir. Dosya kontrolü bu özelliği kullanır.',details:'merhaba → '+T.digest+'\nMerhaba → 7fdc9f4717c5fe66df286c700fab969b4d6209d03aa84624c5f8f58c17c9c058',cards:[['Amaç','Değişiklik kontrolü']]}
);
$('chapter').parentElement.hidden=true;
$('round').parentElement.hidden=true;
$('chapter').replaceChildren(...[...new Set(frames.map(f=>f.chapter))].map(value=>{const option=document.createElement('option');option.value=option.textContent=value;return option;}));
p=0;
render();
